# Generated by Django 5.0.4 on 2024-04-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_marca', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('codigo_familia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion_familia', models.CharField(max_length=100)),
                ('codigo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfamilias', to='maxrainapp.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('ecotasa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('multiplo_cantidad', models.PositiveIntegerField(default=1)),
                ('liquidacion', models.BooleanField(default=False)),
                ('novedad', models.BooleanField(default=False)),
                ('oferta', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('codigo_ean', models.CharField(blank=True, max_length=13, null=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.familia')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.marca')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.usuario')),
            ],
        ),
    ]
