# Generated by Django 5.0.4 on 2024-05-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxrainapp', '0002_alter_articulo_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='familia',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='marca',
        ),
    ]
