# Generated by Django 5.0.4 on 2024-05-22 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxrainapp', '0003_remove_articulo_familia_remove_articulo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='familia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.familia'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.marca'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
