# Generated by Django 5.0.4 on 2024-06-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxrainapp', '0005_carrito_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.articulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxrainapp.usuario')),
            ],
            options={
                'unique_together': {('user', 'articulo')},
            },
        ),
    ]
